name: SCA

on:
  push:
    branches: ["master", "main", "**"]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      additional-arguments: "--exclude=README.md,.jfrog"
      python-version: "3.10"
      pre-scan-commands: |
        echo "Current directory: $(pwd)"
        python3 -m venv venv --upgrade-deps
        source venv/bin/activate
        pip3 install -r requirements.txt
        echo "---"
        echo "Installed packages:"
        pip3 list
    secrets: inherit